config/routes.rb
Rails.application.routes.draw do
    root to: "links#index"
    resources :links, only: [:new, :create, :show]
  end

app/models/link.rb
class Link < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.create(link_params)
    redirect_to @link
  end

  def show
    @link = Link.find(find_links)
  end

  private

  def link_params
    params.require(:link).permit(:title,:url)
  end

  def find_links
    @link = Link.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/index.html.erb
<%= link_to "Submit a new link", new_link_path %>

app/views/links/new.html.erb
<%= form_for @link do |f| %>
  <%= f.text_field :title%>
  <%= f.text_field :url%>
  <%= f.submit "Submit!"%>
<% end %>

app/views/links/show.html.erb
<%=link_to @link.title, @link.url %>